

one_f:
	cargo run f64 one < input.txt >> output.txt

one_b:
	cargo run b32 one < input.txt >> output.txt

two_f:
	cargo run f64 two < input.txt >> output.txt

two_b:	
	cargo run b32 two < input.txt >> output.txt